# ***
# WARNING: Do not EDIT or MERGE this file, it is generated by packagespec.
# ***

LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_ID             := 00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f
LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_TYPE           := base
LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_BASE_LAYER     := 
LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_SOURCE_INCLUDE := 
LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_SOURCE_EXCLUDE := 
LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_CACHE_KEY_FILE := .buildcache/cache-keys/base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f
LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_ARCHIVE_FILE   := .buildcache/archives/00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f.tar.gz
$(eval $(call LAYER,$(LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_ID),$(LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_TYPE),$(LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_BASE_LAYER),$(LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_SOURCE_INCLUDE),$(LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_SOURCE_EXCLUDE),$(LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_CACHE_KEY_FILE),$(LAYER_00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f_ARCHIVE_FILE)))

LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_ID             := 01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4
LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_TYPE           := ui
LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_BASE_LAYER     := 00-base-ac31a4b8dcf1705c7bf5dcbcf45c4ecc816e1d1f
LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_SOURCE_INCLUDE := internal/ui/VERSION
LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_SOURCE_EXCLUDE := 
LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_CACHE_KEY_FILE := .buildcache/cache-keys/ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4
LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_ARCHIVE_FILE   := .buildcache/archives/01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4.tar.gz
$(eval $(call LAYER,$(LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_ID),$(LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_TYPE),$(LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_BASE_LAYER),$(LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_SOURCE_INCLUDE),$(LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_SOURCE_EXCLUDE),$(LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_CACHE_KEY_FILE),$(LAYER_01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4_ARCHIVE_FILE)))

LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_ID             := 02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d
LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_TYPE           := go-modules
LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_BASE_LAYER     := 01-ui-3ae2c7f39d6c530c08f05d94be3170d7ff6f5de4
LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_SOURCE_INCLUDE := go.mod go.sum */go.mod */go.sum
LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_SOURCE_EXCLUDE := 
LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_CACHE_KEY_FILE := .buildcache/cache-keys/go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d
LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_ARCHIVE_FILE   := .buildcache/archives/02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d.tar.gz
$(eval $(call LAYER,$(LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_ID),$(LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_TYPE),$(LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_BASE_LAYER),$(LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_SOURCE_INCLUDE),$(LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_SOURCE_EXCLUDE),$(LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_CACHE_KEY_FILE),$(LAYER_02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d_ARCHIVE_FILE)))

LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_ID             := 03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f
LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_TYPE           := copy-source
LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_BASE_LAYER     := 02-go-modules-5af69a7b1bafcba0a724094e527c8e6f14fa8a9d
LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_SOURCE_INCLUDE := *.go
LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_SOURCE_EXCLUDE := 
LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f
LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_ARCHIVE_FILE   := .buildcache/archives/03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f.tar.gz
$(eval $(call LAYER,$(LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_ID),$(LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_TYPE),$(LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_BASE_LAYER),$(LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_SOURCE_INCLUDE),$(LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_SOURCE_EXCLUDE),$(LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_CACHE_KEY_FILE),$(LAYER_03-copy-source-2839c688d630b3bf449537a62dcf10e66b89bf3f_ARCHIVE_FILE)))
